services:
  - type: web
    name: sb-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.15.0
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    deployment:
      healthCheckTimeoutSeconds: 90
      numInstances: 1
      autoRestart: true
